---
actions:
  injectMavenDependency:
    to: pom.xml
    skip: spring-boot-starter-actuator
---
       <dependency>
         <groupId>org.springframework.boot</groupId>
         <artifactId>spring-boot-starter-actuator</artifactId>
       </dependency>
